### PR TITLE
Add tests for resolving names across hosts

### PR DESCRIPTION
**Pull request by squaremo**
It's more precise to use dig rather than ping. The stock ubuntu image
doesn't come with dig (in package dnsutils), but luckily Aanand made
an image which is exactly ubuntu+dnsutils.

### CODE REVIEW

**Comment by rade** [comment]
I am concerned that we now have no tests that use the resolver library.

**Comment by bboreham** [comment]
I was quite puzzled that this image you are using doesn't have `ping`.  It seems to be quite old, and the standard 'ubuntu' image has grown since then.

**Comment by rade** [comment]
Perhaps one of the other 4782 ubuntu images on the docker hub is the one we want.

**Comment by squaremo** [comment]
> I was quite puzzled that this image you are using doesn't have ping. It seems to be quite old, and the standard 'ubuntu' image has grown since then.

It has `/bin/sh` and `dig`, which are what I need. For ping I can just use the stock Ubuntu image.

**Pull request merged**
